### ISSUE TITLE
Redefine error in "accumulator.h" (commit c52868e)

### ISSUE THREAD

**Issue by Victor-Ch** [jhonnold/berserk#479]
In header accumulator.h:

43   #define UNROLL     128
44   #define UNROLL     16

Obviously it should be:

43   #define UNROLL        128
44   #define NUM_REGS   16

**Comment by jherrera80** [comment]
Also, changes in dad64e04d0392b906a6cd7a5f48aac8082c1b159 seem to have been lost.

**Comment by jhonnold** [comment]
Thank you for this catch Victor. If you'd like to submit a PR for this fix, I'd gladly accept it.

---

@jherrera80 They're lost as the binary cannot support non-vectorized code since [this commit](https://github.com/jhonnold/berserk/commit/8a051d61d7c9a9b60c1d3ffbf5e943d6b9b90b8e). I will work my way back to it, but it is not a top priority to support those between major releases.

**Comment by jhonnold** [comment]
Closing as this was fixed in #482
