### ISSUE TITLE
The nnue validation fails

### ISSUE THREAD

**Issue by Al1953** [jhonnold/berserk#566]
Hi,

Is it possible to compile Berserk-13 for openSUSE?

https://build.opensuse.org/search?search_text=berserk

I was not able to make the compilation. Can't compile with the information listed here...
During compilation the nnue validation fails -- I tried it on opensuse, fedora, mxlinux... (?)

Thanks

```
berserk-13/src> make
Using the current best network: berserk-d43206fe90e4.nn
File already downloaded
Downloaded network berserk-d43206fe90e4.nn failed validation
make ARCH=avx2 all
```

```
/berserk-13/src> make pgo CC=clang
Using the current best network: berserk-d43206fe90e4.nn
File already downloaded
Downloaded network berserk-d43206fe90e4.nn failed validation
```

**Comment by maelic13** [comment]
The problem is in download-network part of makefile. wget creates 0KB file with correct name which fails validation, curl does nothing.

The reason is authentication. `https://berserk-networks.s3.amazonaws.com/berserk-d43206fe90e4.nn` returns `ERROR 403: Forbidden` and so the network cannot be downloaded.

Copying the proper network (downloaded from Berserk 13 release package) into src folder and then compiling works properly.

**Comment by jhonnold** [comment]
Fixed.
